### ISSUE TITLE
[Istanbul] EIP-2129/152: Add Blake2b F Hash Function

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-util#203]
[EIP-2129/152](https://github.com/ethereum/EIPs/pull/2129) adding a [Blake2b F hash function](https://blake2.net/) precompile has been approved for Istanbul in the Ethereum [All Core Devs Call 66](https://github.com/ethereum/pm/pull/115/files#diff-fa6f807129dc50bb67104a64ac1fbeb3R491).

This should likely be added here in the `hash` module first like the `keccak` hash functions and then doing the precompile over on the VM using the functionality from here.

Did a first search, here are two implementations which seems solid and with friendly licensing (both on first sight, needs some confirmation):

- JavaScript: https://github.com/dcposch/blakejs
- WASM: https://github.com/nazar-pc/blake2.wasm

The native vs JS discussion from this issue https://github.com/ethereumjs/ethereumjs-util/issues/195 is relevant in this context analogously.

Update: I updated this with the final decision from ACD 66, there were some rival EIPs before which were discarded.

**Comment by s1na** [comment]
I'd be interested in tackling this once the dust settles and we know the details (and have some test vectors).

**Comment by holgerd77** [comment]
Go ahead! 😀 On a rough look I think usage of Blake2b version of the hash function is already settled independent from the concrete EIP chosen, so I guess we can already start integrating the plain hash function support here?

**Comment by s1na** [comment]
I think EIP-2129 supercedes EIP-2024. EIP-2129 proposes an internal function used for computing a blake2b hash (the blake2b F compression function) as a precompile.

Spec: https://tools.ietf.org/html/rfc7693#section-3.2
PR against geth: https://github.com/keep-network/go-ethereum/pull/4
Implementation of F for the above PR: https://github.com/keep-network/blake2/blob/master/f.go
Relevant function in blakejs: https://github.com/dcposch/blakejs/blob/master/blake2b.js#L119

Blakejs doesn't publicly expose the F compression function. Blake2.wasm doesn't either. I couldn't also find the source for its wasm binary.

I see three options (might not be an exhaustive):

- Implement the F function ourselves.
- Verify that blakejs's compress function corresponds exactly to the F function and ask the maintainer to expose it (if they accept, fork it otherwise). Alternatively use their `blake2bUpdate` function, but make sure to counteract it's side-effects.
- Compile the relevant parts from the reference C implementation to wasm, or wait for a rust implementation and compile that to wasm.

**Comment by axic** [comment]
I wouldn't start working on this before the EIP is merged and has a more complete specification.

**Comment by elizapetrovska** [comment]
> Update: there is this rival [EIP-2129](https://github.com/ethereum/EIPs/pull/2129/files) I just read upon on the ACD Gitter, not sure which one will make it. Please update this post + title once clear.

It was indeed https://github.com/ethereum/EIPs/pull/2129
This might help clarify on the EIP confusion - the core dev call recording, starting with the discussion on 2024 and 2129

https://youtu.be/Cl5zGk-3Ej4?t=2734

**Comment by holgerd77** [comment]
@elizapetrovska Thanks for the reference!

**Comment by holgerd77** [comment]
Updated description and links in the initial post, EIP was now clearly marked as "accepted" in the last ACD 66, should now be ready to be tackled.

**Comment by holgerd77** [comment]
Will be directly integrated in the VM - see https://github.com/ethereumjs/ethereumjs-vm/pull/584 - will close here.
