### ISSUE TITLE
ethjs - elliptic upgrade >6.5.1 ethjs - elliptic need upgrade

### ISSUE THREAD

**Issue by EvertonMelo** [ethereumjs/ethereumjs-util#223]
Please upgrade the dependency. Many projects are being affected with NPM. 

**Timing Attack**
**### Overview**
elliptic is a Fast elliptic-curve cryptography in a plain javascript implementation.

Affected versions of this package are vulnerable to Timing Attack. Practical recovery of the long-term private key generated by the library is possible under certain conditions. Leakage of a bit-length of the scalar during scalar multiplication is possible on an elliptic curve which might allow practical recovery of the long-term private key.

### **Remediation** 
Upgrade elliptic to version 6.5.1 or higher.
link [fixed](https://github.com/indutny/elliptic/commit/7ec66ffa255079260126d87b1762a59ea10de5ea)

**Comment by alcuadrado** [comment]
Thanks for reporting this @EvertonMelo !

I can't find any reference to that timing attack. Do you have a link?

**Comment by EvertonMelo** [comment]
@alcuadrado 

https://github.com/indutny/elliptic/commit/7ec66ffa255079260126d87b1762a59ea10de5ea 
or
https://snyk.io/vuln/SNYK-PYTHON-ECDSA-511942 

If you do not find these links let me know. I draw for you.

**Comment by alcuadrado** [comment]
I'm still a little confused. Can you help me understand this issue? This is my current understanding:

1. A new timing attack was discovered in multiple implementations. It's called Minerva. This is its site: https://minerva.crocs.fi.muni.cz
2. Elliptic is one of those.
3. You know that timing was fixed in 6.5.1, despite no announcement of it.

Note that I'm not doubting about you, just trying to understand what's going on.

Anyhow, we don't depend directly on `elliptic`, but on `secp256k1@^3.0.1`. `secp256k1` has a [caret dependency](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) on `elliptic` `6.x`. So if someone installs this package, they will receive the latest `elliptic` with the fix.

To validate this, I just created an npm package (`npm init -y`), and I got the latest `elliptic`:
```
pato@pmbp:ethjsutil% npm-why elliptic

  Who required elliptic:

  ethjsutil > ethereumjs-util > secp256k1 > elliptic@6.5.1
```

Thanks once again for reporting this, and for helping me understand it.

**Comment by EvertonMelo** [comment]
@alcuadrado 

I don't have time for that, as it is. remain vulnerable.

**Comment by alcuadrado** [comment]
@s1na or @holgerd77, can you double check what I wrote here? I'm pretty sure it is right, but we should be cautious here.

**Comment by holgerd77** [comment]
Thanks @alcuadrado, I would go along with your analysis.

@EvertonMelo I've reverted the personally insulting title you introduced after an answer from @alcuadrado which seemed not to be satisfactory for you.

Please renounce on personal insults or accusations, see our [Code of Conduct](https://ethereumjs.readthedocs.io/en/latest/code_of_conduct.html) here. On repeat I would block you for further comments.

Thanks!

**Comment by EvertonMelo** [comment]
@holgerd77 

funny you have a code of conduct. but there is no code to internalize bugs.

grateful to make the priorities clear.

**Comment by holgerd77** [comment]
@EvertonMelo Please give feedback to the analysis of @alcuadrado, otherwise we would again close here. Thanks!

**Comment by snoopysecurity** [comment]
I think there was a bit of confusion in the Snyk Advisory references which will be fixed later, the original PR from Elliptic which fixes this issue is here: https://github.com/indutny/elliptic/pull/203

**Comment by alcuadrado** [comment]
Thanks for your reply @snoopysecurity! I'll follow that PR.

Can you confirm that if `elliptic` is a transitive dependency of ours (everything with caret deps) we don't have to do anything? Thanks!

**Comment by evertonfraga** [comment]
Great to know @snoopysecurity. 

As the PR is stuck for more than one month now, due to a silly linting error, I raised a PR with a fix here: https://github.com/indutny/elliptic/pull/206.

I'll keep an eye on it.

**Comment by snoopysecurity** [comment]
@alcuadrado Yeah I agree with your above statement, `elliptic` is a transitive dependency used by `secp256k1`, so there is nothing you can do to solve this. `elliptic` will need to fix this and release a new version which can then be used by `secp256k1` to update their elliptic version.

**Comment by alcuadrado** [comment]
Thanks for your confirmation @snoopysecurity.

Let's leave this open to track the upstream change.

**Comment by evertonfraga** [comment]
The `elliptic` maintainer has [implemented the fix](https://github.com/indutny/elliptic/commit/60489415e545efdfd3010ae74b9726facbf08ca8) using a different approach than the original PR, and the package v6.5.2 is out.

I can confirm anyone who depends on `ethereumjs-util` gets the updated version, so I think a release from our side should be unnecessary (tell me otherwise!).

```
npm ls | grep elliptic
│ ├─┬ elliptic@6.5.2
```
