### ISSUE TITLE
Add method for stripping leading hex zeroes

### ISSUE THREAD

**Issue by danfinlay** [ethereumjs/ethereumjs-util#79]
Opening for comment.

Geth recently became [more strict](https://github.com/ethereum/go-ethereum/issues/14477) and now rejects many hex values that have leading zeroes (ie `0x02` instead of `0x2`).

The [official RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) dictates that quantities should have no leading zero, and unformatted data should.

For this reason, it would probably make sense to include some new methods here for creating un-prefixed hex numbers.

I'm curious what kind of API surface people would like for that.  Maybe something as simple as a `stripZeroPrefix()` method?  I could submit that PR in minutes.  We could also have a few new methods, for converting different things to this new type of hex, but that might get more confusing.

Thoughts?  Would a `stripZeroPrefix()` method get merged?

**Comment by axic** [comment]
How about  something along the lines of `shortestHexRepresenation`?

**Comment by Neurone** [comment]
Correct handling of [quantities](https://github.com/trufflesuite/ganache-core/blob/6d20dfd30dd88568a7c025338577cbc3fa16a86d/lib/utils/to.js#L37) and [unformatted data](https://github.com/trufflesuite/ganache-core/blob/6d20dfd30dd88568a7c025338577cbc3fa16a86d/lib/utils/to.js#L48)) is already implemented by ganache-core. I think it is more correct to have those features there because ganache-core is specifically about handling [RPC communications](https://github.com/trufflesuite/ganache-core/tree/df4d6d3ab835b7d77ba7154b38e2cda3a3feee27#implemented-methods).

Maybe those features could be more useful into [ethrpc](https://github.com/ethereumjs/ethrpc), though  reading the project's description it seems they are already there. I didn't find them but notice the output of [rpc.eth.blockNumber()](https://github.com/ethereumjs/ethrpc/tree/7497d5d5c30bf74271dd449e0e94da2c3ca6f70e#basic-rpc).

**Comment by holgerd77** [comment]
This is not about correct handling quantities and data but just about providing a helper function which would transform data into a specific format (which could be e.g. used for correct data transmission in the problem case described above).

Don't see why this shouldn't fit into the scope of this library. I actually prefer the ``stripZeroPrefix()`` naming since this is more explicit about what it does without leaving anything out, ``shortestHexRepresentation()`` is less easy to directly grab the functionality.

**Comment by Neurone** [comment]
My reasoning is this.

- If we want to comply with RPC spec, we must handle data and quantities in correct ways as ganache-core: stripping the prefixed zero is not enough;
- If we don't want to comply with RPC spec, I cannot see any other reasons to have a function to remove the leading 0; I think this can also be misleading and it can bring people to think they can _actually comply_ with RPC spec simply using stripZeroPrefix();

**Comment by holgerd77** [comment]
@Neurone Hmm, this is not specifically for ``RPC``but can be used in different contexts?

**Comment by Neurone** [comment]
@holgerd77 Sorry, but I currently cannot see the usefulness of this in other contexts. The [stripZero()](https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L146) function should be enough for anyone that wants only to remove leading zeros.

**Comment by whymarrh** [comment]
There is prior art for having a strip/trim function that accepts a direction (defaulting to some direction, probably trailing) e.g. Erlang<sup>[\[1\]](http://erlang.org/doc/man/string.html#strip-1)</sup>, Matlab<sup>[\[2\]](https://www.mathworks.com/help/matlab/ref/strip.html)</sup>, and R<sup>[\[3\]](https://stringr.tidyverse.org/reference/str_trim.html#arguments)</sup>. We could introduce a `stripZero` flag that allows us to handle both cases.

**Comment by holgerd77** [comment]
I am actually getting lost here a bit what trim/strip cases we are talking about and what cases are not covered by actual functionality like ``unpad``.

Could you give 4-5 practical in-out examples together with the flag you are suggesting?

**Comment by whymarrh** [comment]
This is offered by `unpad`:

```js
addHexPrefix(unpad('0x00060a24181e4000')) === '0x60a24181e4000'
// => true
```

**Comment by holgerd77** [comment]
Will close in favor of https://github.com/ethereumjs/ethereumjs-monorepo/issues/1302
