### ISSUE TITLE
Can't import ethrereumjs-util in React Native

### ISSUE THREAD

**Issue by amaurymartiny** [ethereumjs/ethereumjs-util#92]
If I create a fresh React Native app with `create-react-native-app`, and only add the line:

```js
import utils from 'ethereumjs-util';
```

I get an error:

![screen shot 2017-08-26 at 5 34 52 pm](https://user-images.githubusercontent.com/1293565/29742763-eae154b4-8a84-11e7-8509-dc3c4761a75c.png)

Edit: After installing the packages manually `yarn add assert`, and then `yarn add stream` and `yarn add buffer`, I get the following error:

![screen shot 2017-08-26 at 5 33 39 pm](https://user-images.githubusercontent.com/1293565/29742753-bfcf9876-8a84-11e7-92b4-3fd6d770affb.png)

**Comment by tharzeez** [comment]
Any solution for this. I tried with rn-nodeify 
[https://www.npmjs.com/package/rn-nodeify](url)

but still I am getting error buffer not defined .. Tried npm install buffer still no hope

**Comment by kouohhashi** [comment]
I have the same issue.
Have you found a solution?

**Comment by tharzeez** [comment]
I followed these steps and in step 9 : 
[https://gist.github.com/dougbacelar/29e60920d8fa1982535247563eb63766](url)
instead of `npm install --save web3`
i installed web3 1.0.0 `npm install --save web3@1.0.0-beta.24`
all those util helper class are available under a single module web3 1.0.0 so yea i can use those util files from the above package.

I hope it helps.

**Comment by axic** [comment]
Fixed by #114.

**Comment by Ouabi54** [comment]
I still not understand how to fix this issue
